export const WORLD_MAP_POLITY_IDS = [
  "polity-byzantine-empire",
  "polity-abbasid-caliphate",
  "polity-holy-roman-empire",
  "polity-chola-empire",
  "polity-goryeo",
  "polity-tokugawa-shogunate",
  "polity-khmer-empire",
  "polity-majapahit",
  "polity-kushan-empire",
  "polity-timurid-empire",
  "polity-maurya-empire",
  "polity-mughal-empire",
  "polity-seljuk-empire",
  "polity-ottoman-empire",
  "polity-frankish-kingdom",
  "polity-kingdom-of-england",
  "polity-fatimid-caliphate",
  "polity-mali-empire",
  "polity-aztec-empire",
  "polity-inca-empire"
] as const;

export const CHINA_MAP_POLITY_IDS = [
  "polity-cn-shang",
  "polity-cn-western-zhou",
  "polity-cn-qin",
  "polity-cn-western-han",
  "polity-cn-eastern-han",
  "polity-cn-cao-wei",
  "polity-cn-shu-han",
  "polity-cn-eastern-wu",
  "polity-cn-northern-wei",
  "polity-cn-tang",
  "polity-cn-northern-song",
  "polity-cn-southern-song",
  "polity-cn-yuan",
  "polity-cn-ming",
  "polity-cn-qing"
] as const;
